//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

pub use super::task_group_ordering::Entity as TaskGroupOrdering;
pub use super::task_groups::Entity as TaskGroups;
pub use super::tasks::Entity as Tasks;
