//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use specta::Type;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, Type)]
#[sea_orm(table_name = "task_groups")]
#[specta(rename = "TaskGroupModel")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub create_date: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::task_group_ordering::Entity")]
    TaskGroupOrdering,
}

impl Related<super::task_group_ordering::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TaskGroupOrdering.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
